# Generated by Django 5.1.3 on 2024-11-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fillprediction_weightprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillprediction',
            old_name='fill_time',
            new_name='fill_date',
        ),
        migrations.RenameField(
            model_name='weightprediction',
            old_name='weight_time',
            new_name='weight_date',
        ),
    ]
