# Generated by Django 5.1.3 on 2024-11-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_timestamp_filllevel_fill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filllevel',
            name='fill_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weightlevel',
            name='weight_date',
            field=models.DateTimeField(null=True),
        ),
    ]
